AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  API Gateway - dummy test 2

  Resources:
    EndpointTest:
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: dist/
        Handler: endpoint
        Runtime: go1.x
        Events:
          MyApi:
          Type: Api
          Properties:
            Method: get
            Path: /endpoint-test